name: Tests

on:
  # TODO: Change the branch to master once merged.
  push:
    branches: [ 'master' ]
  pull_request:

  workflow_dispatch:

# Run the tests
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      # Checks out the repository
      - uses: actions/checkout@v3

      # Set up the matrix Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Upgrade pip
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      # Cache dependencies
      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> "$GITHUB_OUTPUT"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/extras/docs.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install base dependencies
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      # Install dev dependencies
      - name: Install dependencies
        run: python3 -m pip install -r ./extras/dev.txt

      # Run tests
      - name: Test
        run: pytest tests/
